IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'ZenoDb')
BEGIN
    CREATE DATABASE ZenoDb;
END
GO

USE ZenoDb;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Wallets')
BEGIN
    CREATE TABLE Wallets (
        Id UNIQUEIDENTIFIER PRIMARY KEY,
        Name NVARCHAR(50) NOT NULL,
        Description NVARCHAR(200) NOT NULL,
        Balance DECIMAL(18,2) NOT NULL DEFAULT 0,
        CreatedAt DATETIME NOT NULL
    );
END
ELSE
BEGIN
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Wallets' AND COLUMN_NAME = 'InitialBalance')
    BEGIN
        IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Wallets' AND COLUMN_NAME = 'Balance')
        BEGIN
            EXEC sp_rename 'Wallets.InitialBalance', 'Balance', 'COLUMN';
        END
        ELSE
        BEGIN
            ALTER TABLE Wallets DROP COLUMN InitialBalance;
        END
    END

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Wallets' AND COLUMN_NAME = 'Balance')
    BEGIN
        ALTER TABLE Wallets ADD Balance DECIMAL(18,2) NOT NULL DEFAULT 0;
    END
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Entries')
BEGIN
    CREATE TABLE Entries (
        Id UNIQUEIDENTIFIER PRIMARY KEY,
        Title NVARCHAR(100) NOT NULL,
        Value DECIMAL(18,2) NOT NULL,
        Type INT NOT NULL,
        Description NVARCHAR(MAX) NOT NULL,
        Category INT NOT NULL,
        Date DATETIME NOT NULL,
        WalletId UNIQUEIDENTIFIER NOT NULL,
        CONSTRAINT FK_Entries_Wallets FOREIGN KEY (WalletId) REFERENCES Wallets(Id)
    );
END
ELSE
BEGIN
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Entries' AND COLUMN_NAME = 'WalletId')
    BEGIN
        ALTER TABLE Entries ADD WalletId UNIQUEIDENTIFIER NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
        ALTER TABLE Entries ADD CONSTRAINT FK_Entries_Wallets FOREIGN KEY (WalletId) REFERENCES Wallets(Id);
    END
END
GO
