CREATE TABLE IF NOT EXISTS Users (
    Id UUID PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(200) NOT NULL,
    PasswordHash VARCHAR(500) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS IX_Users_Email ON Users(Email);

CREATE TABLE IF NOT EXISTS Wallets (
    Id UUID PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(200),
    UserId UUID NOT NULL,
    Balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    Currency VARCHAR(3) NOT NULL DEFAULT 'BRL',
    CreatedAt TIMESTAMP NOT NULL,
    CONSTRAINT FK_Wallets_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE IF NOT EXISTS Accounts (
    Id UUID PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Bank VARCHAR(100),
    Type VARCHAR(50) NOT NULL DEFAULT 'checking',
    Balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    WalletId UUID NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    CONSTRAINT FK_Accounts_Wallets FOREIGN KEY (WalletId) REFERENCES Wallets(Id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_Accounts_Wallet ON Accounts(WalletId);

CREATE TABLE IF NOT EXISTS Entries (
    Id UUID PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Value NUMERIC(18,2) NOT NULL,
    Type INT NOT NULL,
    Description TEXT NOT NULL,
    Category INT NOT NULL,
    Date TIMESTAMP NOT NULL,
    WalletId UUID NOT NULL,
    CONSTRAINT FK_Entries_Wallets FOREIGN KEY (WalletId) REFERENCES Wallets(Id)
);

CREATE TABLE IF NOT EXISTS Homes (
    Id UUID PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(200) NOT NULL,
    SplitMode INT NOT NULL DEFAULT 0,
    CreatedAt TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS HomeWallets (
    HomeId UUID NOT NULL,
    WalletId UUID NOT NULL,
    CONSTRAINT PK_HomeWallets PRIMARY KEY (HomeId, WalletId),
    CONSTRAINT FK_HomeWallets_Homes FOREIGN KEY (HomeId) REFERENCES Homes(Id),
    CONSTRAINT FK_HomeWallets_Wallets FOREIGN KEY (WalletId) REFERENCES Wallets(Id)
);

CREATE TABLE IF NOT EXISTS HomeExpenses (
    Id UUID PRIMARY KEY,
    HomeId UUID NOT NULL,
    Title VARCHAR(100) NOT NULL,
    Value NUMERIC(18,2) NOT NULL,
    Category INT NOT NULL,
    Month INT NOT NULL,
    Year INT NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    CONSTRAINT FK_HomeExpenses_Homes FOREIGN KEY (HomeId) REFERENCES Homes(Id)
);

CREATE TABLE IF NOT EXISTS Salaries (
    Id UUID PRIMARY KEY,
    UserId UUID NOT NULL,
    WalletId UUID NOT NULL,
    Amount NUMERIC(18,2) NOT NULL,
    Description VARCHAR(200) NOT NULL,
    DayOfMonth INT NOT NULL,
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt TIMESTAMP NOT NULL,
    LastProcessedAt TIMESTAMP NULL,
    CONSTRAINT FK_Salaries_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT FK_Salaries_Wallets FOREIGN KEY (WalletId) REFERENCES Wallets(Id)
);

CREATE TABLE IF NOT EXISTS HomeMembers (
    HomeId UUID NOT NULL,
    UserId UUID NOT NULL,
    Role INT NOT NULL DEFAULT 1,
    JoinedAt TIMESTAMP NOT NULL,
    CONSTRAINT PK_HomeMembers PRIMARY KEY (HomeId, UserId),
    CONSTRAINT FK_HomeMembers_Homes FOREIGN KEY (HomeId) REFERENCES Homes(Id),
    CONSTRAINT FK_HomeMembers_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);
